name: Build

on:
  push:
  pull_request:
  release:
    types:
      - release

jobs:

  build_mingw_toolchain_x86_64:
    name: Mingw-w64 Linux x86_64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Environment Setup
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y
        sudo apt-get install bison bzip2 flex g++ gzip pax build-essential gcc 
    - name: Build Toolchain
      run: |
        BUILD_PREFIX="mingw-w64-toolchain"
        BUILD_VERSION="$(./mingw-w64-build --version | cut -d ' ' -f 2)"
        BUILD_VERSION="${BUILD_VERSION:-0.0.0}"
        BUILD_PLATFORM="linux"
        BUILD_ARCH="x86_64"
        BUILD_TUPLE="${BUILD_PREFIX}-${BUILD_VERSION}-${BUILD_PLATFORM}-${BUILD_ARCH}"
        chmod +x mingw-w64-build
        ./mingw-w64-build --force "${BUILD_ARCH}" "${BUILD_TUPLE}"
        ./mingw-w64-build "${BUILD_ARCH}".clean "${BUILD_TUPLE}"
        ./mingw-w64-build pkgclean "${BUILD_TUPLE}"
        ./mingw-w64-build --list > "${BUILD_TUPLE}"/versions.txt
        tar -cvzf ""${BUILD_TUPLE}".tar.gz" "${BUILD_TUPLE}"
    - name: Upload Release Asset      
      uses: AButler/upload-release-assets@v2.0
      with:
          files: '*.tar.gz'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
  
