name: Build

on:
  push:
  pull_request:
  release:
    types:
      - created

jobs:

  build_mingw_toolchain_x86_64:
    name: Mingw-w64 Linux x86_64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Environment Setup
      run: |
        sudo apt-get install bison bzip2 flex g++ gzip pax build-essential gcc 
    - name: Build Toolchain
      run: |
        chmod 755 mingw-w64-build
        BUILD_VERSION="$(./mingw-w64-build --version | cut -d ' ' -f 2)"
        BUILD_VERSION="${BUILD_VERSION:-0.0.0}"
        ./mingw-w64-build --force x86_64 "mingw-w64-toolchain-${BUILD_VERSION}-linux-x86_64"
        ./mingw-w64-build x86_64.clean "mingw-w64-toolchain-${BUILD_VERSION}-linux-x86_64"
        ./mingw-w64-build pkgclean "mingw-w64-toolchain-${BUILD_VERSION}-linux-x86_64"
        ./mingw-w64-build --list > "mingw-w64-toolchain-${BUILD_VERSION}-linux-x86_64/versions.txt"
        tar -cvzf "mingw-w64-toolchain-${BUILD_VERSION}-linux-x86_64.tar.gz" "mingw-w64-toolchain-${BUILD_VERSION}-linux-x86_64"
    - name: Upload Release Asset
      if: github.event_name == 'release'
      uses: AButler/upload-release-assets@v2.0
      with:
          files: '*.tar.gz'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
  build_mingw_toolchain_i686:
    name: Mingw-w64 Linux i686
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Environment Setup
      run: |
        sudo apt-get install bison bzip2 flex g++ gzip pax build-essential gcc 
    - name: Build Toolchain
      run: |
        chmod 755 mingw-w64-build
        BUILD_VERSION="$(./mingw-w64-build --version | cut -d ' ' -f 2)"
        BUILD_VERSION="${BUILD_VERSION:-0.0.0}"
        ./mingw-w64-build --force i686 "mingw-w64-toolchain-${BUILD_VERSION}-linux-i686"
        ./mingw-w64-build i686.clean "mingw-w64-toolchain-${BUILD_VERSION}-linux-i686"
        ./mingw-w64-build pkgclean "mingw-w64-toolchain-${BUILD_VERSION}-linux-i686"
        ./mingw-w64-build --list > "mingw-w64-toolchain-${BUILD_VERSION}-linux-i686/versions.txt"
        tar -cvzf "mingw-w64-toolchain-${BUILD_VERSION}-linux-i686.tar.gz" "mingw-w64-toolchain-${BUILD_VERSION}-linux-i686"
    - name: Upload Release Asset
      if: github.event_name == 'release'
      uses: AButler/upload-release-assets@v2.0
      with:
          files: '*.tar.gz'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      
  build_mingw_toolchain_mac_x86-64:
    name: Mingw-w64 Mac x86_64
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Toolchain
      run: |
        export MACOSX_DEPLOYMENT_TARGET="10.13"
        chmod 755 mingw-w64-build
        BUILD_VERSION="$(./mingw-w64-build --version | cut -d ' ' -f 2)"
        BUILD_VERSION="${BUILD_VERSION:-0.0.0}"
        ./mingw-w64-build --force x86_64 "mingw-w64-toolchain-${BUILD_VERSION}-mac-x86_64"
        ./mingw-w64-build x86_64.clean "mingw-w64-toolchain-${BUILD_VERSION}-mac-x86_64"
        ./mingw-w64-build pkgclean "mingw-w64-toolchain-${BUILD_VERSION}-mac-x86_64"
        ./mingw-w64-build --list > "mingw-w64-toolchain-${BUILD_VERSION}-mac-x86_64/versions.txt"
        tar -cvzf "mingw-w64-toolchain-${BUILD_VERSION}-mac-x86_64.tar.gz" "mingw-w64-toolchain-${BUILD_VERSION}-mac-x86_64"
    - name: Upload Release Asset
      if: github.event_name == 'release'
      uses: AButler/upload-release-assets@v2.0
      with:
          files: '*.tar.gz'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
  build_mingw_toolchain_mac_i686:
    name: Mingw-w64 Mac i686
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Toolchain
      run: |
        export MACOSX_DEPLOYMENT_TARGET="10.13"
        chmod 755 mingw-w64-build
        BUILD_VERSION="$(./mingw-w64-build --version | cut -d ' ' -f 2)"
        BUILD_VERSION="${BUILD_VERSION:-0.0.0}"
        ./mingw-w64-build --force i686 "mingw-w64-toolchain-${BUILD_VERSION}-mac-i686"
        ./mingw-w64-build i686.clean "mingw-w64-toolchain-${BUILD_VERSION}-mac-i686"
        ./mingw-w64-build pkgclean "mingw-w64-toolchain-${BUILD_VERSION}-mac-i686"
        ./mingw-w64-build --list > "mingw-w64-toolchain-${BUILD_VERSION}-mac-i686/versions.txt"
        tar -cvzf "mingw-w64-toolchain-${BUILD_VERSION}-mac-i686.tar.gz" "mingw-w64-toolchain-${BUILD_VERSION}-mac-i686"
    - name: Upload Release Asset
      if: github.event_name == 'release'
      uses: AButler/upload-release-assets@v2.0
      with:
          files: '*.tar.gz'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
