name: Build

on:
  push:
  pull_request:
  release:
    types:
      - created

jobs:

  build_mingw_toolchain:
    name: MinGW-W64 Toolchain
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Environment Setup
      run: |
        sudo apt-get install bison bzip2 flex g++ gzip pax build-essential gcc 
    - name: Compile Toolchain
      run: |
        chmod 755 *
        ./mingw-w64-build --disable-gdb x86_64 ~/toolchains
        ./mingw-w64-build x86_64.clean
        ./mingw-w64-build pkgclean
        cd /home/runner/toolchains/
        rm -rf build-mingw-w64-x86_64.noindex
        rm -rf source.noindex
        rm -rf pkg
        cd /home/runner
        tar cvzf MinGW-w64.tar.gz toolchains/  
    - name: Upload Release Asset
      if: github.event_name == 'release'
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: /home/runner/MinGW-w64.tar.gz
        asset_name: MinGW-w64.tar.gz
        asset_content_type: application/gzip
      
  build_mingw_toolchain_macOS:
    name: macOS MinGW-W64 Toolchain
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Compile Toolchain
      run: |
        chmod 755 *
        ./mingw-w64-build --disable-gdb x86_64 ~/toolchains
        ./mingw-w64-build x86_64.clean
        ./mingw-w64-build pkgclean
        cd /Users/runner/toolchains/
        rm -rf build-mingw-w64-x86_64.noindex
        rm -rf source.noindex
        rm -rf pkg
        cd /Users/runner/
        tar cvzf macOS_MinGW-w64.tar.gz toolchains/  
    - name: Upload Release Asset
      if: github.event_name == 'release'
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: /Users/runner/macOS_MinGW-w64.tar.gz
        asset_name: macOS_MinGW-w64.tar.gz
        asset_content_type: application/gzip
